language: cpp
os: osx
osx_image: xcode11.3
compiler: gcc

addons:
  homebrew:
    packages:
      - qt
      - open-mesh
      - pugixml
      - bison
      - flex
      - cmake
      - antlr
    update: True

script:
 - cmake . -DCMAKE_INSTALL_PREFIX=$(pwd)/install && make && make install

before_deploy: mkdir artifacts && zip -r artifacts/nome3-macos.zip install

deploy:
  provider: releases
  github_token: 491e001c84e19e9584b8e3ebb8e30db1a1601200
  file_glob: true
  file: "$PWD/artifacts/*"
  skip_cleanup: true
  on:
    repo: randy/Nome3
    tags: true
