language: cpp
os: osx
osx_image: xcode11.3
compiler: gcc
addons:
  homebrew:
    packages:
    - qt
    - open-mesh
    - pugixml
    - bison
    - flex
    - cmake
    - antlr
    update: true
script:
- cmake . -DCMAKE_INSTALL_PREFIX=$(pwd)/install && make && make install
- mkdir artifacts && zip -r artifacts/nome3-macos.zip install
deploy:
  provider: releases
  api_key:
    secure: "U9EUGbWIfzqLsEZkhXNSJ143Xhag8UNo3p8ZmsW3VXdlPtoEtnnssgmW5EhmeRBjaqmCMHfxnEwLbWJVUiGnwWW/E6rk1uyd9BwL8kJZQyur61/C006qJG9CdKgEAhQxd3AukAydAmZ8gabh1zqxImjDCXy/CTHwlGjAJTxkB1kCKY8cxPOet3i1Uw6PRbzl/NgDPtsj6AIuTOTeFl/2LXTF+tfeQcODSvuMLtOiutaF1qukse1LKGU4Mh2UKRACAMRDHQpVNQVxvsS/7EXfpkGuhWwfdFFX4wB/5D2P3u7uoyN7boS4Hff++AqjIpPOQo8l66iAQ688chwigcOIO7vXcEZJt58gndEOvXwLKWC4eNhBFAQuGlltGapRLfk1A+fhuXPY7/clv6CbPRU5ZAYhsbJ0xbq3hpWp7aEUsi8nfJLuq1ebTo7wGGSM3R2QHWraMxiNDjUHQrlwV+FsLB2nP01LPJtsGWsL3Jo2GsoG2xDxa6EapZitpNTHlwPYESVKjRmGKve7pUAQodqcF+KmudnYw8D3bQ24wFPdd1Km2eMGfrJGdBYDAebD8JtzF3+TrBO9bd1RW+RmBaDwnhmeW2+vrqCtwMZpkuRT2nmLItYZYQkqp8SSKBSLpNL2Rg63oFqGJuKbOiAuleqQmsbqi9jzkAzxp6maPjh+6t8="
  file_glob: true
  file: $PWD/artifacts/*
  skip_cleanup: true
  on:
    tags: true
