language: cpp
os: osx
osx_image: xcode11.3
compiler: gcc

addons:
  homebrew:
    packages:
      - qt
      - open-mesh
      - pugixml
      - bison
      - flex
      - cmake
      - antlr
      - opensubdiv
    update: True

script:
 - cmake . -DCMAKE_INSTALL_PREFIX=$(pwd)/install && make && make install

before_deploy: mkdir artifacts && zip -r artifacts/nome3-macos.zip install

deploy:
  provider: releases
  api_key:
    secure: k0ctYj7YaRnxu2rosH447nh94ECOpZMGN7iyFJVYVxuhkGb3hkGZqacAqeYleI3ViynGQmNIb/zif72C6aCqX9LKzEL1NCS9qM9HjEKMUr9OKPfqaykMz+EesTv3fog/TxMiueVjbwQ9UPpqoow0GU8f6/Mj9+urYE92q0in442ie0za1E0OphAx64Cf3a0rSOBC18Ng9wZNnXStXW2OceLRmBd+qyZ6kE1GvXIC0U0dDIB9rE6Bz5FCPvhjB5rVsJ3PK4MiJ12x2xRyBcQQuxLw+R+B1YhlCVEc7alZQTmalUAumOzbNqGxYwPyQ+icmIkP8UBg0aS8OlTAe8DR9lwqlfQYKZVC9LyXW6jKKi+7+sPDrXnLs+CN5Gory6uJR9/sa6QvECog3tCNpln/5Ox/u+rbILdPBUdfq/1Rsmm/6vpNBAnipsEg3MPQ8xGtzVHp7jnWRQyQTKYTKqLyPtufpU7fqvAixbdTyuXwD6DBrUsqxfl/Dhcy8bfU1JrPguIIEz24B6dS8DsXyzHElp70VxERchPjaRm3LPC4as/ak3yzAcRNmvhRpmqrrVFH5uz/iS/lpQ5wyFw6hF0Z88dxpJb1Qeek2xY/KLxlWgrEYDboOA4r/mY7srmLsFFiD7+7HEhlmMyfFtPx/obCDBKsKpHgdwCMyHizMebleGE=
  file_glob: true
  file: "$PWD/artifacts/*"
  skip_cleanup: true
  on:
    repo: randy/NOME3
    tags: true
